frontend:
  image: acrshyam.azurecr.io/frontend
  tag: latest
  replicaCount: 1
  serviceType: NodePort
  port: 30080

backend:
  image: acrshyam.azurecr.io/backend
  tag: latest
  replicaCount: 1
  serviceType: ClusterIP
  port: 8000

env: dev
