frontend:
  image: acrshyam.azurecr.io/frontend
  tag: latest
  replicaCount: 2
  serviceType: NodePort
  port: 30081

backend:
  image: acrshyam.azurecr.io/backend
  tag: latest
  replicaCount: 2
  serviceType: ClusterIP
  port: 8000

env: test
