replicaCount: 1

image:
  repository: acrshyam.azurecr.io/loginpage
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env: dev
